kestra:
  kafka:
    client:
      properties:
        bootstrap.servers: kafka:9092
  elasticsearch:
    client:
      http-hosts: http://elasticsearch:9200
  repository:
    type: elasticsearch
  storage:
    type: local
    local:
      base-path: "/app/storage"
  queue:
    type: kafka
  secret:
    type: jdbc
    jdbc:
      secret: not_really_a_secret_only_for_unit_test
  templates:
    enabled: true
